import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import TailwindIndicator from "@/components/utility/tailwind-indicator";
import Sidebar from "@/components/sidebar/sidebar";
import SidebarWrapper from "@/components/sidebar/sidebar-wrapper";
import React from "react";
import { Toaster } from "sonner";
import ReactQuery from "@/components/utility/react-query";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${inter.className} flex min-h-screen flex-col bg-primary text-primary antialiased md:flex-row`}
      >
        <TailwindIndicator />
        <Toaster />
        <SidebarWrapper>
          <Sidebar />
        </SidebarWrapper>
        <ReactQuery>{children}</ReactQuery>
      </body>
    </html>
  );
}
